---
- name: set root password for mysql
  debconf:
    name: mariadb-server
    question: "{{ item }}"
    vtype: password
    value: "{{ root_db_password }}"
  with_items:
    - mysql-server/root_password
    - mysql-server/root_password_again

- name: Install the Mariadb packages
  apt:
    name: ['mariadb-server', 'python-pymysql']
    state: present

- name: copy 99-openstack.cnf template to destination "/etc/mysql/mariadb.conf.d/99-openstack.cnf"
  template:
    src: 99-openstack.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/99-openstack.cnf
  notify: restart mysql service
